import { BookModel, AuthorModel, Summary3Model } from "@/models";

export const lastBooks: BookModel[] = [
  {
    id: 1,
    title: "The Great Adventure",
    deway_id: 101,
    author_id: 1,
    publisher_id: 1,
    description: "A thrilling journey across the world.",
    pages: 345,
    edition: 1,
    path: "/books/the-great-adventure",
    image_url:
      "https://edit.org/img/blog/yrm-1024-plantillas-ebook-gratis-editables-online.webp",
    published_at: "2020-03-15",
    deway: {
      id: 101,
      code: "123",
      description: "Omaiga3",
      summary_2_id: 12,
      createdAt: "1",
      updatedAt: "1",
      deletedAt: "",
      summary2: {
        id: 102,
        code: "123",
        description: "Omaiga2",
        summary_1_id: 11,
        createdAt: "1",
        updatedAt: "1",
        deletedAt: "",
        summary1: {
          id: 101,
          code: "123",
          description: "Omaiga1",
          createdAt: "1",
          updatedAt: "1",
          deletedAt: "",
        },
      },
    },
    author: {
      id: 1,
      surnames: "Smith",
      names: "John",
      nationality: "American",
      gender: "Male",
      alias: "J. Smith",
      image_url: "https://example.com/authors/john-smith.jpg",
      createdAt: "2015-04-12",
      updatedAt: "2023-01-10",
      deletedAt: "",
    },
    publisher: {
      id: 1,
      name: "Global Books",
      createdAt: "2000-08-22",
      updatedAt: "2023-05-01",
      deletedAt: "",
    },
    createdAt: "2020-03-01",
    updatedAt: "2020-03-10",
    deletedAt: "",
  },
  {
    id: 1,
    title: "The Great Adventure",
    deway_id: 101,
    author_id: 1,
    publisher_id: 1,
    description: "A thrilling journey across the world.",
    pages: 345,
    edition: 1,
    path: "/books/the-great-adventure",
    image_url:
      "https://fondoeditorial.up.edu.pe/wp-content/uploads/2023/12/CARATULA_DI_25-scaled.jpg",
    published_at: "2020-03-15",
    deway: {
      id: 101,
      code: "123",
      description: "Omaiga3",
      summary_2_id: 12,
      createdAt: "1",
      updatedAt: "1",
      deletedAt: "",
      summary2: {
        id: 102,
        code: "123",
        description: "Omaiga2",
        summary_1_id: 11,
        createdAt: "1",
        updatedAt: "1",
        deletedAt: "",
        summary1: {
          id: 101,
          code: "123",
          description: "Omaiga1",
          createdAt: "1",
          updatedAt: "1",
          deletedAt: "",
        },
      },
    },
    author: {
      id: 1,
      surnames: "Smith",
      names: "John",
      nationality: "American",
      gender: "Male",
      alias: "J. Smith",
      image_url: "https://example.com/authors/john-smith.jpg",
      createdAt: "2015-04-12",
      updatedAt: "2023-01-10",
      deletedAt: "",
    },
    publisher: {
      id: 1,
      name: "Global Books",
      createdAt: "2000-08-22",
      updatedAt: "2023-05-01",
      deletedAt: "",
    },
    createdAt: "2020-03-01",
    updatedAt: "2020-03-10",
    deletedAt: "",
  },
  {
    id: 1,
    title: "The Great Adventure",
    deway_id: 101,
    author_id: 1,
    publisher_id: 1,
    description: "A thrilling journey across the world.",
    pages: 345,
    edition: 1,
    path: "/books/the-great-adventure",
    image_url:
      "https://fondoeditorial.up.edu.pe/wp-content/uploads/2023/04/AE99.jpg",
    published_at: "2020-03-15",
    deway: {
      id: 101,
      code: "123",
      description: "Omaiga3",
      summary_2_id: 12,
      createdAt: "1",
      updatedAt: "1",
      deletedAt: "",
      summary2: {
        id: 102,
        code: "123",
        description: "Omaiga2",
        summary_1_id: 11,
        createdAt: "1",
        updatedAt: "1",
        deletedAt: "",
        summary1: {
          id: 101,
          code: "123",
          description: "Omaiga1",
          createdAt: "1",
          updatedAt: "1",
          deletedAt: "",
        },
      },
    },
    author: {
      id: 1,
      surnames: "Smith",
      names: "John",
      nationality: "American",
      gender: "Male",
      alias: "J. Smith",
      image_url: "https://example.com/authors/john-smith.jpg",
      createdAt: "2015-04-12",
      updatedAt: "2023-01-10",
      deletedAt: "",
    },
    publisher: {
      id: 1,
      name: "Global Books",
      createdAt: "2000-08-22",
      updatedAt: "2023-05-01",
      deletedAt: "",
    },
    createdAt: "2020-03-01",
    updatedAt: "2020-03-10",
    deletedAt: "",
  },
];

export const remarkableBooks: BookModel[] = [
  {
    id: 1,
    title: "The Great Adventure",
    deway_id: 101,
    author_id: 1,
    publisher_id: 1,
    description: "A thrilling journey across the world.",
    pages: 345,
    edition: 1,
    path: "/books/the-great-adventure",
    image_url:
      "https://edit.org/img/blog/yrm-1024-plantillas-ebook-gratis-editables-online.webp",
    published_at: "2020-03-15",
    deway: {
      id: 101,
      code: "123",
      description: "Omaiga3",
      summary_2_id: 12,
      createdAt: "1",
      updatedAt: "1",
      deletedAt: "",
      summary2: {
        id: 102,
        code: "123",
        description: "Omaiga2",
        summary_1_id: 11,
        createdAt: "1",
        updatedAt: "1",
        deletedAt: "",
        summary1: {
          id: 101,
          code: "123",
          description: "Omaiga1",
          createdAt: "1",
          updatedAt: "1",
          deletedAt: "",
        },
      },
    },
    author: {
      id: 1,
      surnames: "Smith",
      names: "John",
      nationality: "American",
      gender: "Male",
      alias: "J. Smith",
      image_url: "https://example.com/authors/john-smith.jpg",
      createdAt: "2015-04-12",
      updatedAt: "2023-01-10",
      deletedAt: "",
    },
    publisher: {
      id: 1,
      name: "Global Books",
      createdAt: "2000-08-22",
      updatedAt: "2023-05-01",
      deletedAt: "",
    },
    createdAt: "2020-03-01",
    updatedAt: "2020-03-10",
    deletedAt: "",
  },
  {
    id: 1,
    title: "The Great Adventure",
    deway_id: 101,
    author_id: 1,
    publisher_id: 1,
    description: "A thrilling journey across the world.",
    pages: 345,
    edition: 1,
    path: "/books/the-great-adventure",
    image_url:
      "https://fondoeditorial.up.edu.pe/wp-content/uploads/2023/12/CARATULA_DI_25-scaled.jpg",
    published_at: "2020-03-15",
    deway: {
      id: 101,
      code: "123",
      description: "Omaiga3",
      summary_2_id: 12,
      createdAt: "1",
      updatedAt: "1",
      deletedAt: "",
      summary2: {
        id: 102,
        code: "123",
        description: "Omaiga2",
        summary_1_id: 11,
        createdAt: "1",
        updatedAt: "1",
        deletedAt: "",
        summary1: {
          id: 101,
          code: "123",
          description: "Omaiga1",
          createdAt: "1",
          updatedAt: "1",
          deletedAt: "",
        },
      },
    },
    author: {
      id: 1,
      surnames: "Smith",
      names: "John",
      nationality: "American",
      gender: "Male",
      alias: "J. Smith",
      image_url: "https://example.com/authors/john-smith.jpg",
      createdAt: "2015-04-12",
      updatedAt: "2023-01-10",
      deletedAt: "",
    },
    publisher: {
      id: 1,
      name: "Global Books",
      createdAt: "2000-08-22",
      updatedAt: "2023-05-01",
      deletedAt: "",
    },
    createdAt: "2020-03-01",
    updatedAt: "2020-03-10",
    deletedAt: "",
  },
  {
    id: 1,
    title: "The Great Adventure",
    deway_id: 101,
    author_id: 1,
    publisher_id: 1,
    description: "A thrilling journey across the world.",
    pages: 345,
    edition: 1,
    path: "/books/the-great-adventure",
    image_url:
      "https://fondoeditorial.up.edu.pe/wp-content/uploads/2023/04/AE99.jpg",
    published_at: "2020-03-15",
    deway: {
      id: 101,
      code: "123",
      description: "Omaiga3",
      summary_2_id: 12,
      createdAt: "1",
      updatedAt: "1",
      deletedAt: "",
      summary2: {
        id: 102,
        code: "123",
        description: "Omaiga2",
        summary_1_id: 11,
        createdAt: "1",
        updatedAt: "1",
        deletedAt: "",
        summary1: {
          id: 101,
          code: "123",
          description: "Omaiga1",
          createdAt: "1",
          updatedAt: "1",
          deletedAt: "",
        },
      },
    },
    author: {
      id: 1,
      surnames: "Smith",
      names: "John",
      nationality: "American",
      gender: "Male",
      alias: "J. Smith",
      image_url: "https://example.com/authors/john-smith.jpg",
      createdAt: "2015-04-12",
      updatedAt: "2023-01-10",
      deletedAt: "",
    },
    publisher: {
      id: 1,
      name: "Global Books",
      createdAt: "2000-08-22",
      updatedAt: "2023-05-01",
      deletedAt: "",
    },
    createdAt: "2020-03-01",
    updatedAt: "2020-03-10",
    deletedAt: "",
  },
];

export const authors: AuthorModel[] = [
  {
    id: 1,
    surnames: "Smith",
    names: "John",
    nationality: "American",
    gender: "Male",
    alias: "J. Smith",
    image_url:
      "https://mayneza.com/wp-content/uploads/2019/02/Robert-Greene-autores-libros-superacio%CC%81n-personal-autoayuda-240x300.jpg",
    createdAt: "2015-04-12",
    updatedAt: "2023-01-10",
    deletedAt: "",
  },
  {
    id: 2,
    surnames: "Doe",
    names: "Jane",
    nationality: "British",
    gender: "Female",
    alias: "J. Doe",
    image_url:
      "https://elcomercio-diariocorreo-prod.web.arc-cdn.net/resizer/v2/ISS5NONDOZESXEENHBB4XJPNOY.jpg?auth=52587c1aff407e20f0d7771e8923e0ced511a60b58cf73ef964b715ae38469cd&width=620&smart=true&quality=75",
    createdAt: "2018-09-14",
    updatedAt: "2023-02-15",
    deletedAt: "",
  },
  {
    id: 3,
    surnames: "Gonzalez",
    names: "Carlos",
    nationality: "Mexican",
    gender: "Male",
    alias: "C. Gonzalez",
    image_url:
      "https://cdn.lifestylealcuadrado.com/wp-content/uploads/2012/05/ken_follett_en_madrid.jpg",
    createdAt: "2016-05-20",
    updatedAt: "2023-03-12",
    deletedAt: "",
  },
  {
    id: 4,
    surnames: "Chen",
    names: "Liang",
    nationality: "Chinese",
    gender: "Male",
    alias: "L. Chen",
    image_url:
      "https://mayneza.com/wp-content/uploads/2019/02/Robert-Greene-autores-libros-superacio%CC%81n-personal-autoayuda-240x300.jpg",
    createdAt: "2019-11-10",
    updatedAt: "2023-04-18",
    deletedAt: "",
  },
];
